name: CI

on: [push, pull_request]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-interaction --no-progress

      - name: Start Sail
        run: ./vendor/bin/sail up -d

      - name: Generate APP_KEY
        run: ./vendor/bin/sail artisan key:generate --env=testing

      - name: Run tests
        run: ./vendor/bin/sail artisan test